sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - dev

php:
  - 7.0
  - 7.1
  - 7.2

cache:
  - composer
  - $HOME/.composer/cache

env:
  global:
    - WP_CLI_BIN_DIR=/tmp/wp-cli-phar

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('devpw') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - bash bin/install-package-tests.sh

script: ./vendor/bin/behat
